server.port=8181

backend.base-url=http://localhost:8090/uniworkplanner

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=10000

spring.jackson.serialization.write-dates-as-timestamps=true

logging.level.itm.gestorpendientes=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
